version: '3'
services:

  # backend api container
  backend:
    container_name: river-status-backend
    build: ./backend
    command: yarn server
    expose:
      - ${BACKEND_PORT}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - ./backend:/usr/src/backend
    depends_on:
      - mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USERNAME}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}

  # react frontend container
  frontend:
    container_name: river-status-frontend
    build: ./frontend
    command: yarn start
    expose:
      - ${APP_PORT}
      - ${DEV_WEBSOCKET_PORT}
    ports:
      - ${APP_PORT}:${FRONTEND_PORT}
      - ${DEV_WEBSOCKET_PORT}:${DEV_WEBSOCKET_PORT}
    volumes:
      - ./frontend/src:/usr/src/frontend/src
      - ./frontend/public:/usr/src/frontend/public
    depends_on:
      - backend
    environment:
      API_URL: ${BACKEND_URL}
      API_PORT: ${BACKEND_PORT}

  # mariadb
  mariadb:
    container_name: river-status-mariadb
    image:  mariadb:latest
    expose:
      - ${MARIADB_PORT}
    ports:
      - ${MARIADB_PORT}:${MARIADB_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_USER: ${MARIADB_USERNAME}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}

  # redis container
  redis:
    container_name: river-status-redis
    image:  redis:latest
