version: '3'
services:

  # backend api container
  backend:
    container_name: river-status-backend
    build: ./backend
    command: yarn server
    expose:
      - ${BACKEND_PORT}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - ./backend:/usr/src/backend

  # react frontend container
  frontend:
    container_name: river-status-frontend
    build: ./frontend
    command: yarn start
    expose:
      - ${APP_PORT}
    ports:
      - ${APP_PORT}:${FRONTEND_PORT}
    volumes:
      - ./frontend/src:/usr/src/frontend/src
      - ./frontend/public:/usr/src/frontend/public
    depends_on:
      - backend

  # redis container
  redis:
    container_name: river-status-redis
    image:  redis:latest
