version: '3'
services:

  # backend api container
  backend:
    container_name: river-status-backend
    build: ./backend
    command: yarn server
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - ./backend:/usr/src/backend
    depends_on:
      - mariadb
      - redis
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USERNAME}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_HOST: mariadb
      MARIADB_PORT: ${MARIADB_PORT}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}

  # react frontend container
  frontend:
    container_name: river-status-frontend
    build: ./frontend
    command: yarn start
    ports:
      - ${APP_PORT}:${FRONTEND_PORT}
      - ${DEV_WEBSOCKET_PORT}:${DEV_WEBSOCKET_PORT}
    volumes:
      - ./frontend/src:/usr/src/frontend/src
      - ./frontend/public:/usr/src/frontend/public
    depends_on:
      - backend
    environment:
      API_PORT: ${BACKEND_PORT}

  # mariadb
  mariadb:
    container_name: river-status-mariadb
    image:  mariadb:latest
    ports:
      - ${MARIADB_PORT}:${MARIADB_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_USER: ${MARIADB_USERNAME}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}

  # redis container
  redis:
    container_name: river-status-redis
    image:  redis:latest
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
